SELECT TOP (1000) [Order_ID]
      ,[Order_Date]
      ,[Ship_Date]
      ,[Ship_Mode]
      ,[Customer_Name]
      ,[Category]
      ,[Sub_Category]
      ,[Product_Name]
      ,[Sales]
      ,[Quantity]
      ,[Discount]
      ,[Profit]
      ,[Profit_Margin]
      ,[Order_Category]
  FROM [supermarket].[dbo].[Final_Dashboard_Data]
